services:
  quiz-api:
    image: kuniquoc/quiz_application:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - quiz-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/quiz_application.db

volumes:
  quiz-data:
